apiVersion: apps
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: service
spec:
  replicas: 1
  containers:
    - name: products-service
      image: maurig13/devops-grisi-reyes:products-service-dev # substitute dev for env variable.
      ports:
        - containerPort: 5001
          protocol: TCP
      imagePullPolicy: Always
# ---
# kind: Service
# apiVersion: v1
# metadata:
#   name: service-y
#   namespace: namespace-a
# spec:
#   type: ExternalName
#   externalName: service-y.namespace-b.svc.cluster.local
#   ports:
#   - port: 80
