name: Publish Docker image to ECR

on:
  push:
    branches: ['dev']

env:
  RELEASE_REVISION: 'pr-${{ github.event.pull_request.number }}-${{ github.event.pull_request.head.sha }}'
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: 'us-east-1'

jobs:
  release:
    name: Deploy to EKS
    runs-on: ubuntu-latest
    steps:
      - name: Install kubectl
        uses: azure/setup-kubectl@v2.0
        id: install

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Update kube config
        run: aws eks update-kubeconfig --name devops-grisi-reyes

      - name: Deploy to EKS
        run: |
          kubectl apply -f deployment.yaml

# kubectl apply -f service.yaml
